<<<<<<< HEAD
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
=======
import { ThemeModeScript } from "flowbite-react";
import "./globals.css";
import { Header } from "./components/Header";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};
>>>>>>> cb3d69cf79f447acfd70931fd685e0e7e71f2602

export default function RootLayout({
  children,
}: {
<<<<<<< HEAD
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
=======
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <ThemeModeScript />
      </head>
      <body className="bg-transparent">
        <header>
          <Header />
        </header>
        {children}
      </body>
>>>>>>> cb3d69cf79f447acfd70931fd685e0e7e71f2602
    </html>
  )
}
