import { ThemeModeScript } from "flowbite-react";
import "./globals.css";
import { Header } from "./components/Header";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <ThemeModeScript />
      </head>
      <body className="bg-transparent">
        <header>
          <Header />
        </header>
        {children}
      </body>
    </html>
  );
}
